### ISSUE TITLE
c64 Linker configuration

### ISSUE THREAD

**Issue by daybyter** [puppeh/gcc-6502#2]
Hi!

It seems the c64 Linker configuration lacks the start address in the executable, a basic line to start the generated code and the stack is under the kernal rom?

Claus @ forum64.de wrote a modified cfg File that seems to work better:

http://www.forum64.de/index.php?thread/66857-gcc-6502/&postID=1047882#post1047882

He also wrote a minimal stub for the load address and a basic line to start the code (just 1 sys command to call the machine code).

**Comment by puppeh** [comment]
Fixed by pull request #4, thanks.
