### ISSUE TITLE
Building from source

### ISSUE THREAD

**Issue by mattgodbolt** [puppeh/gcc-6502#7]
Awesome project! I'm the author of a couple of related things... jsbeeb (a 6502 machine, the bbc micro emulator https://bbc.godbolt.org/ ), and Compiler Explorer (https://gcc.godbolt.org). Would love to put this version of GCC on the latter site.

I already build a ton of compilers for CE, and wondered what steps you took to build this patched version. A quick and naive attempt (grab source, run `./contrib/download_prerequistes`) and configure with a prefix...all looks good until:

```
g++ -c  -DIN_GCC_FRONTEND -g -DIN_GCC    -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wno-format -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings -fno-common  -DHAVE_CONFIG_H -I. -Icp -I../.././gcc -I../.././gcc/cp -I../.././gcc/../include -I../.././gcc/../libcpp/include -I/home/matthew/dev/gcc-6502/host-x86_64-unknown-linux-gnu/gmp -I/home/matthew/dev/gcc-6502/gmp -I/home/matthew/dev/gcc-6502/host-x86_64-unknown-linux-gnu/mpfr -I/home/matthew/dev/gcc-6502/mpfr -I/home/matthew/dev/gcc-6502/mpc/src  -I../.././gcc/../libdecnumber -I../.././gcc/../libdecnumber/bid -I../libdecnumber -I../.././gcc/../libbacktrace -I/home/matthew/dev/gcc-6502/host-x86_64-unknown-linux-gnu/isl/include -I/home/matthew/dev/gcc-6502/isl/include  -o cp/friend.o -MT cp/friend.o -MMD -MP -MF cp/.deps/friend.TPo ../.././gcc/cp/friend.c
In file included from ../.././gcc/cp/except.c:1027:0:
cfns.gperf: In function ‘const char* libc_name_p(const char*, unsigned int)’:
cfns.gperf:101:1: error: ‘const char* libc_name_p(const char*, unsigned int)’ redeclared inline with ‘gnu_inline’ attribute
cfns.gperf:26:14: note: ‘const char* libc_name_p(const char*, unsigned int)’ previously declared here
cfns.gperf: At global scope:
cfns.gperf:26:14: warning: inline function ‘const char* libc_name_p(const char*, unsigned int)’ used but never defined
```

Before I head off patching things (which I do to build GCCs for the CE site: https://github.com/mattgodbolt/compiler-explorer-image/tree/master/gcc/build/patches - the cfns patch is proably the one ... am I doing something wrong?

Cheers!

**Comment by mattgodbolt** [comment]
Ok, `--target 6502` helps :) hahah

**Comment by mattgodbolt** [comment]
I get a lot further, but with: `./configure --prefix ~/dev/gcc-6502-staging --target 6502 --enable-languages=c --disable-bootstrap` I get:

checking for suffix of object files... configure: error: in `/home/matthew/dev/gcc-6502/6502/libgcc':
configure: error: cannot compute suffix of object files: cannot compile

-- what magic do I need to disable building `libgcc`, or to point it at a 6502 version? Thanks in advance!

**Comment by mattgodbolt** [comment]
Ah, just found puppeh/gcc-6502-bits

**Comment by itszor** [comment]
Hi! It'll be super-cool to have 6502 GCC support in the compiler explorer. Thank you!

(I have https://github.com/puppeh/vc4-toolchain/ too for the Raspberry Pi, etc. VideoCore4 chip, but that might be slightly less fun.)
